"""
ComfyUI-DreamFit Nodes
"""

from .dreamfit_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_NAMES
from .dreamfit_encode import NODE_CLASS_MAPPINGS as ENCODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ENCODE_DISPLAY_NAMES
from .dreamfit_adapter import NODE_CLASS_MAPPINGS as ADAPTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ADAPTER_DISPLAY_NAMES
from .dreamfit_sampler import NODE_CLASS_MAPPINGS as SAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY_NAMES

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(ENCODE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(ADAPTER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SAMPLER_MAPPINGS)

# Combine all display name mappings
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_DISPLAY_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(ENCODE_DISPLAY_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(ADAPTER_DISPLAY_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SAMPLER_DISPLAY_NAMES)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']